version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "url_shortener_app"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data: {}